using Api.Domain.Common;
using Api.Domain.Enums;

namespace Api.Domain.Entities;

public class Ticket : AuditableEntity, ITenantScoped
{
    public Guid CompanyId { get; set; }
    public Company? Company { get; set; }

    public Guid ConversationId { get; set; }
    public Conversation? Conversation { get; set; }

    /// <summary>
    /// Human-readable per-company number, e.g. #1, #2, #42.
    /// Generated by TicketService using MAX+1 inside a transaction — not a DB
    /// sequence so it stays per-tenant and gap-free within a company's own list.
    /// </summary>
    public int TicketNumber { get; set; }

    public string Subject { get; set; } = string.Empty;
    public TicketStatus Status { get; set; } = TicketStatus.Open;
    public TicketPriority Priority { get; set; } = TicketPriority.Medium;

    /// <summary>Free-text team name, e.g. "Finance", "IT", "Support". Nullable — unassigned teams are allowed.</summary>
    public string? AssignedTeam { get; set; }

    public Guid? AssignedToId { get; set; }
    public Agent? AssignedTo { get; set; }

    /// <summary>Why escalation was triggered — stored for agent context, e.g. "Low AI confidence (0.45)" or "Customer requested human agent".</summary>
    public string? EscalationReason { get; set; }

    public DateTime? ResolvedAt { get; set; }
}
